### ISSUE TITLE
BTree(Key|Value)Iterator cannot be constructed out of module

### ISSUE THREAD

**Issue by zneak** [lorentey/BTree#14]
While the BTree class is exposed to allow mere mortals to create collections based on it, the `BTreeKeyIterator` and `BTreeValueIterator` types have internal accessors and cannot be constructed from outside the `BTree` module. That feels somewhat inconsistent.

**Comment by lorentey** [comment]
I felt these two types were too simple to be worth extending much effort on designing their public API; they're pretty much implementation details for `List` and `OrderedSet`. I wouldn't oppose documenting their initializers and making them public, though — PR, please :)

**Comment by zneak** [comment]
Sure. Which branch would you prefer the PR to target?

**Comment by lorentey** [comment]
I think it should go into `swift3` for now.

Károly

**Comment by lorentey** [comment]
BTree 4.0.0 includes a sorted multiset collection; this eliminates the primary usecase for making `BTreeKeyIterator`'s initializer public. (Please reopen this issue if you still need it.)
