### ISSUE TITLE
Swift Package Manager errors

### ISSUE THREAD

**Issue by timvermeulen** [lorentey/BTree#23]
If I try to import this package using SPM, I get an error saying that the test folder has an unsupported layout, and that it can be fixed by moving those files inside a module. So, moving the test files into a separate folder (e.g. `Tests/BTreeTests/...` should fix it. :)

**Comment by lorentey** [comment]
Interesting; this still worked a couple of weeks ago. It looks like I'll need to release 4.0.1 soon!

**Comment by lorentey** [comment]
Thanks for reporting this! 👍🏼
