### ISSUE TITLE
Crash when inserting Element in List

### ISSUE THREAD

**Issue by AymanRadid** [lorentey/BTree#3]
Using the following function I am trying to benchmark the performance of this List

<img width="344" alt="capture" src="https://cloud.githubusercontent.com/assets/4644467/13491818/ed63415c-e134-11e5-95f0-97000b40673e.png">

I get the following error on line 183 BTreeNode
EXC_BAD_INSTRUCTION fatal error: Array index out of range.

The index where this happens is 682.

**Comment by lorentey** [comment]
Very nice catch, thank you! 
It was caused by a regression during refactoring that wasn't caught by the test suite.
